### ISSUE TITLE
后台数据库文件 SQL有吗

### ISSUE THREAD

**Issue by logofun** [OneCodeMonkey/tp5_bbs#1]
这个后台数据库文件在哪下啊

**Comment by OneCodeMonkey** [comment]
这是个很普通的 bbs项目，但基本的功能是满足的。一会我传个 template 模板文件就能用了

**Comment by OneCodeMonkey** [comment]
sql 在 doc/ 下，https://raw.githubusercontent.com/OneCodeMonkey/tp5_bbs/master/docs/tp5_bbs.sql
